-- MySQL Script generated by MySQL Workbench
-- Wed Oct 26 13:07:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fruit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fruit` ;

-- -----------------------------------------------------
-- Schema fruit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fruit` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fruit` ;

-- -----------------------------------------------------
-- Table `fruit`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruit`.`user` ;

CREATE TABLE IF NOT EXISTS `fruit`.`user` (
                                              `id` BIGINT NOT NULL AUTO_INCREMENT,
                                              `email` VARCHAR(255) NULL DEFAULT NULL ,
    `password` VARCHAR(255) NULL DEFAULT NULL,
    `first_name` VARCHAR(255) NULL DEFAULT NULL,
    `last_name` VARCHAR(255) NULL DEFAULT NULL,
    `token` VARCHAR(255) NULL DEFAULT NULL,
    `status` INT NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fruit`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruit`.`address` ;

CREATE TABLE IF NOT EXISTS `fruit`.`address` (
                                                 `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                 `city` VARCHAR(255) NULL DEFAULT NULL,
    `district` VARCHAR(255) NULL DEFAULT NULL,
    `ward` VARCHAR(255) NULL DEFAULT NULL,
    `street` VARCHAR(255) NULL DEFAULT NULL,
    `description` VARCHAR(255) NULL DEFAULT NULL,
    `status` INT NULL DEFAULT NULL,
    `user_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`, `user_id`),
    INDEX `fk_address_user1_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `fk_address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fruit`.`user` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fruit`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruit`.`category` ;

CREATE TABLE IF NOT EXISTS `fruit`.`category` (
                                                  `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                  `name` VARCHAR(255) NULL DEFAULT NULL,
    `status` INT NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fruit`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruit`.`product` ;

CREATE TABLE IF NOT EXISTS `fruit`.`product` (
                                                 `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                 `name` VARCHAR(255) NULL DEFAULT NULL,
    `price` BIGINT NULL DEFAULT NULL,
    `description` TEXT NULL DEFAULT NULL,
    `discount` INT NULL DEFAULT NULL,
    `quantity` INT NULL DEFAULT NULL,
    `status` INT NULL DEFAULT NULL,
    `category_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`, `category_id`),
    INDEX `fk_product_category1_idx` (`category_id` ASC) VISIBLE,
    CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `fruit`.`category` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fruit`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruit`.`image` ;

CREATE TABLE IF NOT EXISTS `fruit`.`image` (
                                               `id` BIGINT NOT NULL AUTO_INCREMENT,
                                               `link` VARCHAR(255) NULL DEFAULT NULL,
    `product_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_image_product1_idx` (`product_id` ASC) VISIBLE,
    CONSTRAINT `fk_image_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `fruit`.`product` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fruit`.`shipping_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruit`.`shipping_status` ;

CREATE TABLE IF NOT EXISTS `fruit`.`shipping_status` (
                                                         `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                         `name` VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fruit`.`voucher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruit`.`voucher` ;

CREATE TABLE IF NOT EXISTS `fruit`.`voucher` (
                                                 `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                 `code` VARCHAR(255) NULL DEFAULT NULL,
    `cost` BIGINT NULL DEFAULT NULL,
    `start_date` DATETIME NULL DEFAULT NULL,
    `end_date` DATETIME NULL DEFAULT NULL,
    `times` INT NULL DEFAULT NULL,
    `status` INT NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fruit`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruit`.`order` ;

CREATE TABLE IF NOT EXISTS `fruit`.`order` (
                                               `id` BIGINT NOT NULL AUTO_INCREMENT,
                                               `shipping_cost` BIGINT NULL DEFAULT NULL,
                                               `total` BIGINT NULL DEFAULT NULL,
                                               `description` VARCHAR(255) NULL DEFAULT NULL,
    `created_date` VARCHAR(255) NULL DEFAULT NULL,
    `shipping_status_id` BIGINT NOT NULL,
    `address_id` BIGINT NOT NULL,
    `voucher_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_order_shipping_status1_idx` (`shipping_status_id` ASC) VISIBLE,
    INDEX `fk_order_address1_idx` (`address_id` ASC) VISIBLE,
    INDEX `fk_order_voucher1_idx` (`voucher_id` ASC) VISIBLE,
    CONSTRAINT `fk_order_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `fruit`.`address` (`id`),
    CONSTRAINT `fk_order_shipping_status1`
    FOREIGN KEY (`shipping_status_id`)
    REFERENCES `fruit`.`shipping_status` (`id`),
    CONSTRAINT `fk_order_voucher1`
    FOREIGN KEY (`voucher_id`)
    REFERENCES `fruit`.`voucher` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fruit`.`order_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruit`.`order_detail` ;

CREATE TABLE IF NOT EXISTS `fruit`.`order_detail` (
                                                      `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                      `price` BIGINT NULL DEFAULT NULL,
                                                      `quantity` INT NULL DEFAULT NULL,
                                                      `discount` INT NULL DEFAULT NULL,
                                                      `product_id` BIGINT NOT NULL,
                                                      `order_id` BIGINT NOT NULL,
                                                      PRIMARY KEY (`id`),
    INDEX `fk_order_detail_product1_idx` (`product_id` ASC) VISIBLE,
    INDEX `fk_order_detail_order1_idx` (`order_id` ASC) VISIBLE,
    CONSTRAINT `fk_order_detail_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `fruit`.`order` (`id`),
    CONSTRAINT `fk_order_detail_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `fruit`.`product` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fruit`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruit`.`role` ;

CREATE TABLE IF NOT EXISTS `fruit`.`role` (
                                              `id` BIGINT NOT NULL AUTO_INCREMENT,
                                              `name` VARCHAR(255) NULL DEFAULT NULL,
    `status` INT NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fruit`.`role_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruit`.`user_role` ;

CREATE TABLE IF NOT EXISTS `fruit`.`user_role` (
                                                   `role_id` BIGINT NOT NULL,
                                                   `user_id` BIGINT NOT NULL,
                                                   PRIMARY KEY (`role_id`, `user_id`),
    INDEX `fk_user_role_user1_idx` (`user_id` ASC) VISIBLE,
    INDEX `fk_user_role_role_idx` (`role_id` ASC) VISIBLE,
    CONSTRAINT `fk_user_role_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `fruit`.`role` (`id`),
    CONSTRAINT `fk_user_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fruit`.`user` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fruit`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruit`.`cart` ;

CREATE TABLE IF NOT EXISTS `fruit`.`cart` (
                                              `id` BIGINT NOT NULL AUTO_INCREMENT,
                                              `quantity` INT NULL,
                                              `user_id` BIGINT NOT NULL,
                                              `product_id` BIGINT NOT NULL,
                                              PRIMARY KEY (`id`),
    INDEX `fk_cart_user1_idx` (`user_id` ASC) VISIBLE,
    INDEX `fk_cart_product1_idx` (`product_id` ASC) VISIBLE,
    CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fruit`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_cart_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `fruit`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
ALTER TABLE `fruit`.`user_role`
    ADD PRIMARY KEY (`user_id`, `role_id`);
;
ALTER TABLE `fruit`.`product`
    CHANGE COLUMN `description` `description` TEXT NULL DEFAULT NULL ;