use fruit
-- category
INSERT INTO `fruit`.`category` (`name`, `status`) VALUES ('Trái cây xuất khẩu', '1');
INSERT INTO `fruit`.`category` (`name`, `status`) VALUES ('Trái cây nhập khẩu', '1');
INSERT INTO `fruit`.`category` (`name`, `status`) VALUES ('Trái cây nội địa', '1');
-- product
INSERT INTO `fruit`.`product` (`name`, `price`, `description`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Dừa xiêm trọc Bến Tre size M (450-600g/trái)', '20700', '<div><h3><strong><span style=\"font-size:14px\">Ưu điểm của dừa Xiêm&nbsp;trọc Bến Tre là gì?</span></strong></h3><p><span style=\"font-size:14px\">- Nhỏ gọn, không chiếm quá nhiều diện tích vì đã gọt sạch vỏ hoàn toàn.</span></p><p><span style=\"font-size:14px\">- Có thể giữ được rất lâu ở điều kiện bình thường và thời gian sẽ kéo dài đến 45 ngày nếu được bảo quản ở nhiệt độ từ 2 - 5 độ C.</span></p><p><span style=\"font-size:14px\">- Thích hợp để bạn mang theo khi đi du lịch, dã ngoại, mang đi học hoặc đi làm.</span></p><p><span style=\"font-size:14px\">- Được chọn từ dừa xiêm Bến Tre nên đảm bảo có hương vị thơm ngon, mát lành từ tự nhiên, giúp giải khát tức thì cho ngày hè oi bức.</span></p><h3><strong><span style=\"font-size:14px\">Hướng dẫn uống dừa Xiêm&nbsp;trọc Bến Tre</span></strong></h3><p><span style=\"font-size:14px\">Với dừa gọt trọc Bến Tre, bạn sẽ có thể dễ dàng uống được chỉ với một vài thao tác rất đơn giản. Sau khi được gọt toàn bộ phần vỏ bên ngoài, quả dừa sẽ xuất hiện các mắt dừa và đây chính là nơi để bạn cắm ống hút vào uống.</span></p><p><span style=\"font-size:14px\">Sau khi đã uống xong phần nước dừa, tiếp theo bạn sẽ dùng sống dao đập nhẹ ở xung quanh đầu nhọn của quả dừa và nó sẽ tự động nứt ra. Lúc này, bạn cần dùng tay tách nhẹ nhàng lớp vỏ này ra để ăn được phần cơm dừa bên trong.&nbsp;</span></p><h3><strong><span style=\"font-size:14px\">Cách bảo quản dừa Xiêm&nbsp;trọc Bến Tre để giữ được lâu</span></strong></h3><p><span style=\"font-size:14px\">Dừa gọt trọc có thể giữ được khoảng 30 ngày nếu như được bảo quản ở nhiệt độ chuẩn là 2 - 5 độ C mà không sợ có vi khuẩn xâm nhập nhờ lớp vỏ dày và cứng bảo vệ.&nbsp;</span></p><p><span style=\"font-size:14px\">Nếu bảo quản ở những nơi thoáng mát, tránh ánh nắng trực tiếp thì bạn có thể giữ được dừa gọt trọc trong khoảng 1 tuần.</span></p><h3><strong><span style=\"font-size:14px\">Mua dừa Xiêm trọc Bến&nbsp;Tre&nbsp;ở đâu tại tp HCM</span></strong></h3><p><span style=\"font-size:14px\">Tình trạng thị trường trái cây phong phú hiện nay với sự xuất hiện của các mặt hàng không rõ nguồn gốc, kém chất lượng, thật giả lẫn lộn thì Bio Ngon&nbsp;là địa chỉ tin cậy để người tiêu dùng ghé mua trái cây, đặc biệt là mua dừa Xiêm trọc Bến Tre&nbsp;ở TPHCM.</span></p><p><span style=\"font-size:14px\">Các loại trái cây tại Bio Ngon đạt an toàn vệ sinh, đúng chất lượng, canh tác theo hướng hữu cơ tiêu chuẩn 6 KHÔNG, nhằm đảm bảo cho sức khỏe cho mọi nhà.</span></p><p><span style=\"font-size:14px\">Tiêu chuẩn 6 KHÔNG:</span></p><p><span style=\"font-size:14px\">•&nbsp;&nbsp;&nbsp;&nbsp;Không hóa chất kích thích tăng trưởng.</span></p><p><span style=\"font-size:14px\">•&nbsp;&nbsp;&nbsp;&nbsp;Không hóa chất diệt côn trùng, sâu hại.</span></p><p><span style=\"font-size:14px\">•&nbsp;&nbsp;&nbsp;&nbsp;Không hóa chất diệt cỏ.</span></p><p><span style=\"font-size:14px\">•&nbsp;&nbsp;&nbsp;&nbsp;Không hóa chất bảo quản.</span></p><p><span style=\"font-size:14px\">•&nbsp;&nbsp;&nbsp;&nbsp;Không hóa chất chống úng.</span></p><p><span style=\"font-size:14px\">•&nbsp;&nbsp;&nbsp;&nbsp;Không phân bón hóa học.</span></p><h3><strong><span style=\"font-size:14px\">Mua dừa Xiêm trọc&nbsp;trực tiếp tại website hoặc liên hệ:</span></strong></h3><p><span style=\"font-size:14px\">Fanpage: <strong><a href=\"http://m.me/biongon.raulanhcanhngot\">Bio Ngon</a></strong></span></p><p><span style=\"font-size:14px\">Hotline:&nbsp;0786416477</span></p><p><span style=\"font-size:14px\">Zalo:&nbsp;<a href=\"https://zalo.me/2384430608336986569\"><strong>Bio Ngon</strong></a></span></p></div>', '10', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Bưởi da xanh (Trái 1,2kg)', '70200', '5', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Dưa hấu dài (Trái 2kg)', '54000', '10', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Dưa hấu không hạt (Trái 2,5kg)', '76500', '3', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Vú Sữa Lò Rèn (Kg)', '141000', '5', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Bưởi da xanh (Kg)', '58500', '7', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Cam xoàn (kg)', '53100', '1', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Chanh dây vàng ngọt(900-1000g/túi)', '112500', '3', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Bưởi đường lá cam Tân Triều (Trái 1kg)', '67500', '6', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Mãng cầu Thái ( Kg)', '85500', '2', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Bơ sáp 034 (Kg)', '52000', '2', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Ổi nữ hoàng (Kg)', '27000', '2', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Ổi Ruby ruột đỏ (Kg)', '25650', '5', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`,`category_id`) VALUES ('Cam sành trái lớn (Kg)', '45000', '4', '20', '1','3');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Cam Cara ruột đỏ Úc (Kg)', '150000', '5', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Cherry Mỹ (Kg)', '5500000', '50', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Dâu Tây Hàn Quốc (Kg)', '290000', '5', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Dâu Úc (Kg)', '169000', '5', '20', '1', '2');

INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Nho Mẫu Đơn Đỏ Hàn Quốc', '1500000', '0', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Nho Mẫu Đơn Shine Muscat Hàn Quốc', '1400000', '0', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Na Dai Đài Loan', '799000', '0', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Sầu riêng Musang King Malaysia', '699000', '0', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Nho Xanh Mỹ', '395000', '2', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Táo Envy Size 24 Mỹ', '350000', '2', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Chà Là Khô Natural Delights Organic Medjool Dates (Hộp Xanh)', '349999', '1', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Nho Đen Mỹ', '300000', '1', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Kiwi Vàng New Zealand', '299000', '10', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Lê Hàn Quốc (1 hộp 3 trái)', '299000', '10', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Táo Rockit New Zealand', '199000', '19', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Lê Hàn Quốc', '199000', '4', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Lê Nam Phi', '155000', '4', '20', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Táo Ambrosia size 88 Mỹ', '149000', '1', '2', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Táo Xanh Granny Smith Mỹ', '145000', '1', '10', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Việt Quất Mỹ', '145000', '1', '10', '1', '2');
INSERT INTO `fruit`.`product` (`name`, `price`, `discount`, `quantity`, `status`, `category_id`) VALUES ('Dưa Lưới Đài Loan', '169000', '1', '10', '1', '2');

-- image
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/traicay-duaxiem_7ca1dbab69fe45d5a64f9e3b43cbbb01_large.jpg', '15');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/traicay-buoi-da-xanh_7ee8e580fbfb4736947a49c1589a7367_large.jpg', '16');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/traicay-duahaudai_8dadb14c05064c89bdd2d12b344e570b_large.jpg', '17');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/traicay-duahau_73cc0f4e90de4ba2b05df2d61744fe60_large.jpg', '18');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/vu-su-lo-ren_7a423dea140746eb9eb3e2364cd71623_large.jpg', '19');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/traicay-buoi-da-xanh_30353400301e45719de6b0686b8dc59a_large.jpg', '20');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/traicay-camxoan_c9f82a571c094fb691f70dc5b68e5d73_large.jpg', '21');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/traicay-chanhday_72c5d74ba0b94477a131fc21038df567_large.jpg', '22');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/buoiduonglacam-cthc_44c29c6fdc2640468e14c57be14da736_large.jpg', '23');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/mangcauthai-cthc_f669687815834e178281bffbd24559e5_large.jpg', '24');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/traicay-bosap_830419154ff74e9582ba45c99c55832a_large.jpg', '25');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/traicay-oinuhoang_857a1a551b244d3184a31c795c7005f8_large.jpg', '26');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/traicay-oiruby_682a34ee2e904942998f8d3f240e40a9_large.jpg', '27');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('https://product.hstatic.net/200000271661/product/traicay-cam-sanh_b4fa5d31619649c9a51e18fba4e9ee2f_large.jpg', '28');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('http://www.viettropfruit.com/wp-content/uploads/2016/09/cam-cara-ruou-do-uc-300x300.png', '29');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('http://www.viettropfruit.com/wp-content/uploads/2016/11/cherry-uc-300x300.jpg', '30');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('http://www.viettropfruit.com/wp-content/uploads/2016/12/Dau-tay-han-quoc-300x300.jpg', '31');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('http://www.viettropfruit.com/wp-content/uploads/2016/11/5ec44a6ad804f55bfd0588e4fcc7779c-300x300.jpg', '32');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('nho-mau-don-djo-han-quoc.jpg', '33');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('nho-mau-djon-shine-muscat-han-quoc.jpg', '34');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('nho-mau-djon-shine-muscat-han-quoc-2.jpg', '34');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('na-dai-dai-loan.jpg', '35');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('na-dai-dai-loan-2.jpg', '35');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('na-dai-dai-loan-3.jpg', '35');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('sau-rieng-musang-king-malaysia.png', '36');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('sau-rieng-musang-king-malaysia-2.png', '36');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('sau-rieng-musang-king-malaysia-3.png', '36');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('nho-xanh-my.jpg', '37');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-envy-size-24-my.png', '38');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-envy-size-24-my-2.jpg', '38');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-envy-size-24-my-3.jpg', '38');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('cha-la-kho-natural-delights-organic-medjool-dates-hop-xanh.png', '39');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('nho-den-my-vinfruits-1-min-900x900.jpg', '40');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('nho-den-my-vinfruits-2-min-900x900.jpg', '40');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('nho-den-my-vinfruits-3-min-900x900.jpg', '40');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('nho-den-my-vinfruits-4-min-900x900.jpg', '40');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('kiwi-vang-newzealand-vinfruits-2-min-900x900.jpg', '41');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('kiwi-vang-newzealand-vinfruits-1-min-900x900.jpg', '41');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('kiwi-vang-newzealand-vinfruits-7-min-900x900.jpg', '41');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('kiwi-vang-newzealand-vinfruits-6-min-900x900.jpg', '41');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('le-han-quoc-vinfruits-2-min-900x900.jpg', '44');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('le-han-quoc-vinfruits-4-min-900x900.jpg', '44');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('le-han-quoc-vinfruits-5-min-900x900.jpg', '44');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('le-han-quoc-vinfruits-6-min-900x900.jpg', '44');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-juliet-organic-88-phap.jpg', '43');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-juliet-organic-88-phap-2.jpg', '43');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-juliet-organic-88-phap-3.jpg', '43');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('le-han-quoc.jpg', '42');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('le-nam-phi-vinfruits-7-min-900x900.jpg', '45');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('le-nam-phi-vinfruits-8-min-900x900.jpg', '45');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('le-nam-phi-vinfruits-5-min-900x900.jpg', '45');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('le-nam-phi-vinfruits-3-min-900x900.jpg', '45');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-ambrosia-size-88-my.jpg', '46');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-ambrosia-size-88-my-2.jpg', '46');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-ambrosia-size-88-my-3.jpg', '46');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-ambrosia-size-88-my-3.jpg', '46');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-xanh-my-vinfruits-6-900x900.jpg', '47');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-xanh-my-vinfruits-10-900x900.jpg', '47');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-xanh-my-vinfruits-5-900x900.jpg', '47');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('tao-xanh-my-vinfruits-8-900x900.jpg', '47');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('viet-quat-my-vinfruits-2-900x900.jpg', '48');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('viet-quat-my-vinfruits-3-900x900.jpg', '48');
INSERT INTO `fruit`.`image` (`link`, `product_id`) VALUES ('viet-quat-my-vinfruits-1-900x900.jpg', '48');


